### ISSUE TITLE
Practica 7-hilos-Edwin Ortiz Cruz

### ISSUE THREAD

**Issue by EdwinOrtiz1412** [SistemasTecTlaxiaco/practica-final-de-hilos-topicosavanzados-ide#2]
[Practica7_Hilos con Windows form_ 4US.pdf](https://github.com/SistemasTecTlaxiaco/practica-final-de-hilos-topicosavanzados-ide/files/8546101/Practica7_Hilos.con.Windows.form_.4US.pdf)

**Comment by Gregorio012** [comment]
Calificación 19

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
